apiVersion: v1    
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  #MYSQL_DATABASE: c3NjX2Ri #ssc_db
  MYSQL_USER: c3NjdXNlcg== #sscuser
  MYSQL_PASSWORD: U3NjVXNlckAxMjM= #SscUser@123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  MYSQL_DATABASE: SSC_DB
  MYSQL_DATABASE_URL: jdbc:mysql://mysql/SSC_DB
  my.cnf: |-
    [client]
    port = 3306
    socket = /var/run/mysqld/mysqld.sock
    [mysql]
    no-beep
    socket = /var/run/mysqld/mysqld.sock
    [mysqld]
    collation-server = latin1_general_cs
    init-connect = 'SET NAMES latin1'
    character-set-server = latin1
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    port = 3306
    datadir = /var/lib/mysql/data
    default_authentication_plugin = mysql_native_password
    default-storage-engine = INNODB
    sql-mode = "TRADITIONAL"
    long_query_time=10
    report_port = 3306
    lower_case_table_names = 1
    secure-file-priv = NULL
    symbolic-links = 0
    max_connections = 151
    table_open_cache = 2000
    tmp_table_size = 648M
    thread_cache_size = 10
    myisam_max_sort_file_size = 100G
    myisam_sort_buffer_size = 2G
    key_buffer_size = 8M
    read_buffer_size = 64K
    read_rnd_buffer_size = 256K
    innodb_flush_log_at_trx_commit = 1
    innodb_log_buffer_size = 1M
    innodb_buffer_pool_size = 10G
    innodb_log_file_size = 5G
    innodb_lock_wait_timeout = 300
    innodb_thread_concurrency = 9
    innodb_autoextend_increment = 64
    innodb_buffer_pool_instances = 8
    innodb_concurrency_tickets = 5000
    innodb_old_blocks_time = 1000
    innodb_open_files = 300
    innodb_stats_on_metadata = 0
    innodb_file_per_table = 1
    innodb_checksum_algorithm = 0
    back_log = 80
    flush_time = 0
    join_buffer_size = 256K
    max_allowed_packet = 1G
    max_connect_errors = 100
    open_files_limit = 4161
    sort_buffer_size = 256K
    table_definition_cache = 1400
    binlog_row_event_max_size = 8K
    sync_master_info = 10000
    sync_relay_log = 10000
    sync_relay_log_info = 10000
    #!includedir /etc/mysql/conf.d/
    [mysqldump]
    max_allowed_packet = 1G
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: bikvol
  labels:
    volume: bikvol
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/pv-data/bikvol
    type: ''
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Available
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: bikvol
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  capacity:
    storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    role: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
    role: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      role: mysql
  template:
    metadata:
      labels:
        app: mysql
        role: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: data
              mountPath: /var/lib/mysql/data
      volumes:
        - name: mysql-persistent-storage
          configMap:
            name: mysql-config
        - name: data
          persistentVolumeClaim:
            claimName: myclaim
