kind: PersistentVolume
apiVersion: v1
metadata:
  name: bikvol
  labels:
    volume: bikvol
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/pv-data/bikvol
    type: ''
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Available
